# MongoDB数据库配置
spring:
  data:
    mongodb:
      # 数据库带权限验证 格式：mongodb://用户名:密码@ip:port/database name
      uri: mongodb://admin:123456@192.168.239.134:27017/example?authSource=admin&authMechanism=SCRAM-SHA-1
      # 数据库不带权限验证
      #uri: mongodb://192.168.239.134:27017/example